=== Peggyvthlk/ErgasiaXML/dtd_thema1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT customerList (company|person)*>
<!ELEMENT company (company_info, package_offer+)>
<!ELEMENT person (person_info, package_offer+)>
<!ATTLIST company CompCodeNo ID #REQUIRED>
<!ATTLIST person PersonCodeNo ID #REQUIRED>
<!ELEMENT company_info (name, VAT_number, tax_office, address)>
<!ELEMENT person_info (first_name, middle_name?, surname, VAT_number, tax_office, address)>
<!ELEMENT package_offer (giving+, tel_number*, startPrice, finalPrice?, in_discount?, contract_start_date?, contract_end_date?)>
<!ATTLIST package_offer contract_number ID #REQUIRED>
<!ATTLIST package_offer package_category (B_START|B_LITE|P_LITE|P_START|B_all|P_all|B_smart|P_smart) #REQUIRED>
<!ELEMENT giving (#PCDATA)>
<!ELEMENT tel_number (#PCDATA)>
<!ELEMENT startPrice (#PCDATA)>
<!ELEMENT finalPrice (#PCDATA)>
<!ELEMENT in_discount (discount_rate, amount_after_discount)>
<!ELEMENT discount_rate (#PCDATA)>
<!ELEMENT amount_after_discount (#PCDATA)>
<!ELEMENT contract_start_date (#PCDATA)>
<!ELEMENT contract_end_date (#PCDATA)>
<!ATTLIST startPrice unitS CDATA "euro">
<!ATTLIST startPrice forperiodS CDATA "month">
<!ATTLIST finalPrice unitF CDATA "euro">
<!ATTLIST finalPrice forperiodF CDATA "month">
<!ATTLIST amount_after_discount unit CDATA "euro">
<!ATTLIST amount_after_discount forperiod CDATA "month">
<!ELEMENT name (#PCDATA)>
<!ELEMENT VAT_number (#PCDATA)>
<!ELEMENT tax_office (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT middle_name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>

=== Peggyvthlk/ErgasiaXML/xml_thema1a.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE customerList SYSTEM "dtd_thema1.dtd">
<customerList>

    <company CompCodeNo="c12345">
        <company_info>
            <name> CompanyX </name>
            <VAT_number> 123456789 </VAT_number>
            <tax_office> office1 </tax_office>
            <address> lampraki 25 </address>
        </company_info>

        <package_offer contract_number="no5" package_category="B_START">
            <giving> SMS </giving>
            <giving> Internet </giving>
            <tel_number> 2101234567 </tel_number>
            <startPrice> 300 </startPrice>
            <finalPrice> 270 </finalPrice>
            <in_discount>
                <discount_rate> 10% </discount_rate>
                <amount_after_discount> 270 </amount_after_discount>
            </in_discount>
            <contract_start_date> 06/11 </contract_start_date>
            <contract_end_date> 12/12 </contract_end_date>
        </package_offer>
    </company>

</customerList>

=== Peggyvthlk/ErgasiaXML/xml_thema1b.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE customerList SYSTEM "dtd_thema1.dtd">
<customerList>

    <person PersonCodeNo="67890">
        <person_info>
            <first_name> Maria </first_name>
            <surname> Papadopoulou </surname>
            <tax_office> office2 </tax_office>
            <address> lampraki 12 </address>
        </person_info>

        <package_offer contract_number="8">
            <giving> Internet </giving>
            <tel_number> 2109876543 </tel_number>
            <startPrice> 520 </startPrice>
            <finalPrice> 210 </finalPrice>
            <contract_start_date> 06/11</contract_start_date>
            <contract_end_date> 12/12 </contract_end_date>
        </package_offer>
    </person>

</customerList>
